# Generated by Django 2.2.6 on 2019-11-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_auto_20191121_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('IPL', 'O_ITEM_PLACED'), ('IPD', 'O_ITEM_PICKED'), ('INA', 'O_ITEM_NOT_AVAILABLE'), ('IRD', 'O_ITEM_REMOVED'), ('IRJ', 'O_ITEM_REJECTED')], default=('IPL', 'O_ITEM_PLACED'), max_length=3),
        ),
    ]
