# Generated by Django 2.2.6 on 2019-11-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_auto_20191121_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_note',
            field=models.CharField(default='NONE', max_length=200, null=True),
        ),
    ]
