# Generated by Django 2.2.6 on 2019-11-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_auto_20191123_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='location_state',
            field=models.CharField(choices=[('KA', 'STATE_KARNATAKA'), ('KL', 'STATE_KERALA'), ('TN', 'STATE_TAMIL_NADU'), ('AP', 'STATE_ANDRA_PRADESH'), ('MH', 'STATE_MAHARASTRA')], default='KA', max_length=80),
        ),
    ]
