# Generated by Django 2.2.6 on 2019-12-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_auto_20191129_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status_note',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='location_state',
            field=models.CharField(choices=[('KA', 'KARNATAKA'), ('KL', 'KERALA'), ('TN', 'TAMIL_NADU'), ('AP', 'ANDRA_PRADESH'), ('MH', 'MAHARASTRA')], default='KA', max_length=80),
        ),
    ]
