# Generated by Django 2.2.6 on 2019-12-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_auto_20191203_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=8, unique=True)),
                ('driving_liscence_pic', models.ImageField(blank=True, upload_to='media/proof_details')),
                ('pan_card_pic', models.ImageField(blank=True, upload_to='media/proof_details')),
                ('rc_pic', models.ImageField(blank=True, upload_to='media/proof_details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'DR'}, on_delete=django.db.models.deletion.CASCADE, related_name='da_proofs', to='base_app.UserProfileInfo')),
            ],
        ),
    ]
