# Generated by Django 2.2.6 on 2019-12-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_auto_20191206_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daprofile',
            name='driving_liscence_pic',
            field=models.ImageField(blank=True, upload_to='proof_details'),
        ),
        migrations.AlterField(
            model_name='daprofile',
            name='pan_card_pic',
            field=models.ImageField(blank=True, upload_to='proof_details'),
        ),
        migrations.AlterField(
            model_name='daprofile',
            name='rc_pic',
            field=models.ImageField(blank=True, upload_to='proof_details'),
        ),
    ]
