

REF_ID_PREF_BUSINESS_AGENT = "BSA"
REF_ID_PREF_CONSUMER = "CRR"
REF_ID_PREF_DELIVERY_AGENT = "DLA"
REF_ID_PREF_DELIVERY_MANAGER = "DMR"
REF_ID_PREF_SUPER_ADMIN = "SAM"
REF_ID_PREF_ORDER = "O19"
REF_ID_PREF_ORDER_ITEM = "OIM19"

SERVER_PREFIX = "http://127.0.0.1:8000/"
