# User types under business users
USER_TYPE_SUPER_ADMIN = 'SR'
USER_TYPE_MANAGER = 'MR'
USER_TYPE_DELIVERY_AGENT = 'DR'
USER_TYPE_CONSUMER = 'CR'
USER_TYPE_BUSINESS_OWNER = 'BO'

USER_TYPES = [
        (USER_TYPE_SUPER_ADMIN, 'SUPER_ADMIN'),
        (USER_TYPE_MANAGER, 'MANAGER'),
        (USER_TYPE_CONSUMER, 'CONSUMER'),
        (USER_TYPE_DELIVERY_AGENT, 'DELIVERY_AGENT'),
        (USER_TYPE_BUSINESS_OWNER, 'BUSINESS_OWNER'),
     ]

USER_TYPES_DIC = dict(USER_TYPES)
# User status

USER_STATUS_ACTIVE ='AT'
USER_STATUS_INACTIVE = 'IA'
USER_STATUS_DISABLED = 'DS'
USER_STATUS_DELETED = 'DL'

USER_STATUS = [
        (USER_STATUS_ACTIVE, 'ACTIVE'),
        (USER_STATUS_INACTIVE, 'INACTIVE'),
        (USER_STATUS_DISABLED, 'DISABLED'),
        (USER_STATUS_DELETED, 'DELETED'),
    ]


USER_STATUS_DIC = dict(USER_STATUS)

STATUS_ACTIVE ='AT'
STATUS_INACTIVE = 'IA'
STATUS_DISABLED = 'DS'
STATUS_DELETED = 'DL'


STATUS = [
        (STATUS_ACTIVE, 'ACTIVE'),
        (STATUS_INACTIVE, 'INACTIVE'),
        (STATUS_DISABLED, 'DISABLED'),
        (STATUS_DELETED, 'DELETED'),
    ]


STATUS_DIC = dict(STATUS)

VAL_STR_DEFAULT = "NONE"

# business store status


BUSINESS_STATUS_ACTIVE ='AT'
BUSINESS_STATUS_INACTIVE = 'IA'
BUSINESS_STATUS_DISABLED = 'DS'
BUSINESS_STATUS_DELETED = 'DL'

BUSINESS_STORE_STATUS = [
        (BUSINESS_STATUS_ACTIVE, 'ACTIVE'),
        (BUSINESS_STATUS_INACTIVE, 'INACTIVE'),
        (BUSINESS_STATUS_DISABLED, 'DISABLED'),
        (BUSINESS_STATUS_DELETED, 'DELETED'),
    ]

BUSINESS_STORE_STATUS_DIC = dict(BUSINESS_STORE_STATUS)

# order status

ORDER_PLACED ='OPD'
ORDER_CONFIRMED_BY_CUSTOMER = 'OCC'
ORDER_PICKEDUP = 'OPU'
ORDER_DELIVERED = 'ODD'
ORDER_CANCELLED = 'OCD'


ORDER_STATUS = [
(ORDER_PLACED, 'ORDER_PLACED'),
(ORDER_CONFIRMED_BY_CUSTOMER, 'ORDER_CONFIRMED_BY_CUSTOMER'),
(ORDER_PICKEDUP, 'ORDER_PICKEDUP'),
(ORDER_DELIVERED, 'ORDER_DELIVERED'),
(ORDER_CANCELLED, 'ORDER_CANCELLED')
]

ORDER_STATUS_DIC = dict(ORDER_STATUS)


#order item
O_ITEM_PLACED = 'IPL'
O_ITEM_PICKED = 'IPD'
O_ITEM_NOT_AVAILABLE = 'INA'
O_ITEM_REMOVED = 'IRD'
O_ITEM_REJECTED = 'IRJ'

O_ITEM_STATUS = [
(O_ITEM_PLACED, 'O_ITEM_PLACED'),
(O_ITEM_PICKED,'O_ITEM_PICKED'),
(O_ITEM_NOT_AVAILABLE, 'O_ITEM_NOT_AVAILABLE'),
(O_ITEM_REMOVED,'O_ITEM_REMOVED'),
(O_ITEM_REJECTED, 'O_ITEM_REJECTED'),
]

O_ITEM_STATUS_DIC = dict(O_ITEM_STATUS)


# state list

STATE_TAMIL_NADU = "TN"
STATE_KERALA = "KL"
STATE_KARNATAKA = "KA"
STATE_ANDRA_PRADESH = "AP"
STATE_MAHARASTRA = "MH"

STATE_LIST = [
(STATE_KARNATAKA, "KARNATAKA"),
(STATE_KERALA, "KERALA"),
(STATE_TAMIL_NADU, "TAMIL_NADU"),
(STATE_ANDRA_PRADESH, "ANDRA_PRADESH"),
(STATE_MAHARASTRA, "MAHARASTRA")
]

STATE_LIST_DICT = dict(STATE_LIST)
